name: PSYCHO Ngrok RDP

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Restart-Service -Name TermService -Force

      - name: Create User
        run: |
          $username = "CLOUD_PSYCHO"
          $password = "Psycho@2026#"
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser -Name $username -Password $securePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member $username

      - name: Download & Start Ngrok
        run: |
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/b4p73zGM573/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"
          Expand-Archive ngrok.zip -DestinationPath .
          .\ngrok.exe config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389"
          Start-Sleep -Seconds 5
          
          # Get Ngrok TCP Address
          $log = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
          $address = $log.tunnels[0].public_url -replace 'tcp://', ''
          
          Write-Host "`n==============================================`n"
          Write-Host "CONNECT ADDRESS : $address"
          Write-Host "USERNAME        : CLOUD_PSYCHO"
          Write-Host "PASSWORD        : Psycho@2026#"
          Write-Host "`n==============================================`n"

      - name: Maintain Loop
        run: |
          while ($true) {
              Start-Sleep -Seconds 300
          }
